# -*- coding: UTF-8 -*-

"""
RULES = {
	file: {
		'define': define,
		'id': id,
		'index': index,
		'depend': depend,
		'share': share,
		'feature': feature,
	},
	...
}
file：String，CSV/XML文件名（相对于conf目录），可支持递归目录，可支持通配符匹配多个，可支持逗号隔开多个，CSV/XML文件不可混合
define：String，定义器定义（相对于exporters目录），必须包含TYPE,DEFINE设置
id：String或者String Tuple，选填，指定该文件导出项的索引字段，用于确定ID字段，CSV中为列名，XML中为属性名，默认为"id"
index：String，选填，指定该文件导出项的索引名称，用于其他导出器作为ID检查
depend：String或者String Tuple，选填，在导出该文件之前必须完成的导出文件，每个设置必须属于RULES中的某个file字段，如果出现环形依赖则报错
share：Const，选填，指定DATA导出文件存放处，默认为COMMON
	COMMON，该文件为服务端、客户端共享
	SERVER，该文件为服务端独占
	CLIENT，该文件为客户端独占
	SPLIT，该文件为按具体定义器定义分割
feature：Const Tuple，选填，指定导出该文件需要遵循的特征，可设置多个
	DENY_DEL，对比DATA导出目录中的对应DATA文件，如果没有对应DATA文件，则设置不生效，禁止删除已有项
	DENY_ADD，条件同上，禁止增加未知项
	IGNORE_TITLE，仅适用于CSV，忽略表头与定义器中定义顺序和选填列检查
	CHECK_BLINE，仅适用于CSV，检查空行
	EACH_EXPORT，将file中每个文件导出为一个单独的JSON文件，文件名使用每个文件的路径转义，定义器为共用
	EXP_FILE，指定载入、导出的DATA文件将以.json.exp后缀名进行

"""

COMMON = 1
SERVER = 2
CLIENT = 3
SPLIT = 4

DENY_DEL = 1
DENY_ADD = 2
IGNORE_TITLE = 3
CHECK_BLINE = 4
EACH_EXPORT = 5
EXP_FILE = 6

RULES = {
	'W物品/1武器.xlsx':{
		'define':'weapon',
		'sheet':'武器',
		'id':'id',
		'share':COMMON,
	},
	'W物品/3头盔.xlsx':{
		'define':'helmet',
		'sheet':'头盔',
		'id':'id',
		'share':COMMON,
	},
	'W物品/2盔甲.xlsx':{
		'define':'armor',
		'sheet':'盔甲',
		'id':'id',
		'share':COMMON,
	},
	'W物品/4项链.xlsx':{
		'define':'necklace',
		'sheet':'项链',
		'id':'id',
		'share':COMMON,
	},
	'W物品/6鞋子.xlsx':{
		'define':'shoe',
		'sheet':'鞋子',
		'id':'id',
		'share':COMMON,
	},
	'W物品/5戒指.xlsx':{
		'define':'ring',
		'sheet':'戒指',
		'id':'id',
		'share':COMMON,
	},
	'W物品/7宝石.xlsx':{
		'define':'gem',
		'sheet':'宝石',
		'id':'id',
		'share':COMMON,
	},
	'W物品/8材料.xlsx':{
		'define':'material',
		'sheet':'材料',
		'id':'id',
		'share':COMMON,
	},
	'W物品/9杂物.xlsx':{
		'define':'item',
		'sheet':'杂物',
		'id':'id',
		'share':COMMON,
	},
	'W物品/10魂石.xlsx':{
		'define':'soul_stone',
		'sheet':'魂石',
		'id':'id',
		'share':COMMON,
	},
	'W物品/14魔灵.xlsx':{
		'define':'soul',
		'sheet':'魔灵',
		'id':'id',
		'share':COMMON,
	},
	'W物品/15扫荡券.xlsx':{
		'define':'sweep',
		'sheet':'扫荡券',
		'id':'id',
		'share':COMMON,
	},
	'W物品/换装配置.xlsx':{
		'define':'equip',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'W物品/物品id总表.xlsx':{
		'define':'item_id',
		'sheet':'id',
		'id':'id',
		'depend':('W物品/9杂物.xlsx', 
				'W物品/10魂石.xlsx', 
				'W物品/14魔灵.xlsx', 
				'W物品/8材料.xlsx', 
				'W物品/7宝石.xlsx', 
				'W物品/11装备激活碎片.xlsx', 
				'W物品/12装备强化石.xlsx', 
				'W物品/13代币.xlsx', 
				'W物品/5戒指.xlsx', 
				'W物品/1武器.xlsx', 
				'W物品/3头盔.xlsx', 
				'W物品/2盔甲.xlsx', 
				'W物品/4项链.xlsx', 
				'W物品/6鞋子.xlsx', 
				'W物品/15扫荡券.xlsx', 
				'W物品/16钻石金币.xlsx'
				),
		'share':COMMON,
	},
	'Z战斗/技能.xlsx':{
		'define':'skill',
		'sheet':'技能',
		'id':('id','星级'),
		'share':COMMON,
	},
	'Z战斗/buff.xlsx':{
		'define':'buff',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'Z战斗/怪物技能.xlsx':{
		'define':'monster_skill',
		'sheet':'技能',
		'id':('模型id','状态名'),
		'share':COMMON,
	},
	'Z战斗/怪物模型.xlsx':{
		'define':'monster_model',
		'sheet':'怪物',
		'id':'id',
		'share':COMMON,
	},
	'Z战斗/怪物.xlsx':{
		'define':'monster',
		'sheet':'怪物',
		'id':'id',
		'share':COMMON,
	},
	'Z战斗/人物等级变化量.xlsx':{
		'define':'level',
		'sheet':'Sheet',
		'id':'等级',
		'share':COMMON,
	},
	'副本.xlsx':{
		'define':'fuben',
		'sheet':'副本',
		'id':'关卡id',
		'share':COMMON,
	},
	'场景.xlsx':{
		'define':'scene',
		'sheet':'场景',
		'id':'场景id',
		'share':COMMON,
	},
	'多语言.xlsx':{
		'define':'language',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'对话.xlsx':{
		'define':'dialog',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'气泡对话.xlsx':{
		'define':'bubble_dia',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'单机测试.xlsx':{
		'define':'offline',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'基础操作教学.xlsx':{
		'define':'tutor',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'新手引导.xlsx':{
		'define':'guide',
		'sheet':'Sheet1',
		'id':'步骤id',
		'share':COMMON,
	},
	'玩家状态标记.xlsx':{
		'define':'guide_state',
		'sheet':'State',
		'id':'状态id',
		'share':COMMON,
	},
	'邮件.xlsx':{
		'define':'email',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'塔防刷怪.xlsx':{
		'define':'shuaguai',
		'sheet':'Sheet1',
		'id':('关卡id','第几批'),
		'share':COMMON,
	},
	'随机名字.xlsx':{
		'define':'namelist',
		'sheet':'随机名字',
		'id':('id','id'),
		'share':COMMON,
	},
	'Z战斗/魔灵升级.xlsx':{
		'define':'soul_upgrade',
		'sheet':'魔灵升级',
		'id':'魔灵等级',
		'share':COMMON,
	},
	'Z战斗/魔灵进化.xlsx':{
		'define':'soul_evolution',
		'sheet':'魔灵进化',
		'id':'进化星级',
		'share':COMMON,
	},
	'W物品/装备强化.xlsx':{
		'define':'equipment_strengthen',
		'sheet':'装备强化',
		'id':('品质','部位','等级区间'),
		'share':COMMON,
	},
	'W物品/商店物品库.xlsx':{
		'define':'store_item',
		'sheet':'物品库',
		'id':'商品id',
		'share':COMMON,
	},
	'W物品/普通商店.xlsx':{
		'define':'shop1',
		'sheet':'普通商店',
		'id':'随机库id',
		'share':SERVER,
	},
	'W物品/黑市商店.xlsx':{
		'define':'shop2',
		'sheet':'黑市商店',
		'id':'随机库id',
		'share':SERVER,
	},
	'R任务/任务.xlsx':{
		'define':'quest',
		'sheet':'任务',
		'id':'id',
		'share':COMMON,
	},
	'R任务/任务条件.xlsx':{
		'define':'quest_condition',
		'sheet':'任务条件',
		'id':'id',
		'share':COMMON,
	},
	'活动和公告/活动.xlsx':{
		'define':'activities',
		'sheet':'活动',
		'id':'id',
		'share':CLIENT,
	},
	'活动和公告/公告.xlsx':{
		'define':'notice',
		'sheet':'公告',
		'id':'id',
		'share':CLIENT,
	},
	'商城.xlsx':{
		'define':'mall',
		'sheet':'商城',
		'id':'id',
		'share':COMMON,
	},
	'兑换商城.xlsx':{
		'define':'exchange_mall',
		'sheet':'兑换商城',
		'id':'商品id',
		'share':COMMON,
	},
	'vip.xlsx':{
		'define':'vip',
		'sheet':'vip',
		'share':COMMON,
	},
	'体力购买.xlsx':{
		'define':'energy_purchase',
		'sheet':'体力购买',
		'id':'购买次数',
		'share':COMMON,
	},
	'RMB.xlsx':{
		'define':'rmb_cost',
		'sheet' :'RMB',
		'id':'id',
		'share':COMMON,
	},
	'W物品/精通强化.xlsx':{
		'define':'avatar_strengthen',
		'sheet':'精通强化',
		'id':'id',
		'share':COMMON,
	},
	'W物品/装备强化消耗.xlsx':{
		'define':'equipment_lv',
		'sheet':'装备碎片',
		'id':('品质', '等级'),
		'share':COMMON,
	},
	'W物品/装备激活.xlsx':{
		'define':'equipment_activation',
		'sheet':'装备激活',
		'id':('品质', '部位'),
		'share':COMMON,
	},
	'W物品/11装备激活碎片.xlsx':{
		'define':'equip_frag',
		'sheet':'装备激活碎片',
		'id':'id',
		'share':COMMON,
	},
	'W物品/12装备强化石.xlsx':{
		'define':'equip_qh_stone',
		'sheet':'装备强化石',
		'id':'id',
		'share':COMMON,
	},
	'W物品/13代币.xlsx':{
		'define':'token_coin',
		'sheet':'代币',
		'id':'id',
		'share':COMMON,
	},
	'W物品/抽奖花金币.xlsx':{
		'define':'lottery',
		'sheet':'物品',
		'id':'id',
		'depend':('W物品/物品id总表.xlsx',),
		'share':COMMON,
	},
	'W物品/抽奖花钻石.xlsx':{
		'define':'lottery2',
		'sheet':'物品',
		'id':'id',
		'depend':('W物品/物品id总表.xlsx',),
		'share':COMMON,
	},
	'签到/每日签到.xlsx':{
		'define':'sign_in',
		'sheet':'每日签到',
		'id':'日期',
		'share':COMMON,
	},
	'boss挑战.xlsx':{
		'define':'boss_battle',
		'sheet':'Sheet1',
		'id':'跳转关卡',
		'share':COMMON,
	},
	'点金手.xlsx':{
		'define':'midas_touch',
		'sheet':'点金手',
		'id':'次数',
		'share':COMMON,
	},
	'物品获取途径.xlsx':{
		'define':'guide_tips',
		'sheet':'Sheet1',
		'id':'物品ID',
		'share':CLIENT,
	},
	'宝箱掉落.xlsx':{
		'define':'box_drop',
		'sheet':'Sheet1',
		'id':'宝箱ID',
		'share':COMMON,
	},
	'W物品/16钻石金币.xlsx':{
		'define':'diamond_gold',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	
	'屏蔽词库.xlsx':{
		'define':'illegal_word',
		'sheet':'Sheet1',
		'id':'id',
		'share':CLIENT,
	},
	'Z战斗/scenebuff.xlsx':{
		'define':'scenebuff',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'英雄试炼.xlsx':{
		'define':'hero_pratice',
		'sheet':'Sheet1',
		'id':'场景ID',
		'share':CLIENT,
	},
	'功能开启控制.xlsx':{
		'define':'sub_sys_switch',
		'sheet':'主UI功能',
		'id':'ID',
		'share':COMMON,
	},
	'W物品/翅膀.xlsx':{
		'define':'wing',
		'sheet':'Sheet1',
		'id':'id',
		'share':COMMON,
	},
	'按钮控制.xlsx':{
		'define':'button_control',
		'sheet':'Sheet1',
		'id':'ID',
		'share':COMMON,
	},
}
